//
// Created by hannes on 2020/10/31.
//

#ifndef COS214PROJECT_AERODYNAMICSFACTORY_H
#define COS214PROJECT_AERODYNAMICSFACTORY_H


class AerodynamicsFactory {

};


#endif //COS214PROJECT_AERODYNAMICSFACTORY_H
